"""baseline v1.0.0 schema

Revision ID: 1c9b09f02432
Revises:
Create Date: 2026-04-28 12:36:45.813890

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c9b09f02432"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("payload_json", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.create_index("idx_activity_events_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index("idx_activity_events_source", ["source"], unique=False)
        batch_op.create_index("idx_activity_events_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dedup_key", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("plant_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("payload_json", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("first_seen_at", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.Integer(), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("acknowledged_at", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedup_key"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index("idx_alerts_dedup_key", ["dedup_key"], unique=False)
        batch_op.create_index("idx_alerts_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index("idx_alerts_status", ["status"], unique=False)

    op.create_table(
        "clusters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("environment", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "decision_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("evaluated_at", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("interval_hours", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("primary_code", sa.String(), nullable=True),
        sa.Column("reason_text", sa.String(), nullable=False),
        sa.Column("payload_json", sa.String(), nullable=False),
        sa.Column("triggered_by", sa.String(), nullable=False),
        sa.Column("actuated", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("decision_logs", schema=None) as batch_op:
        batch_op.create_index("idx_decision_logs_cluster_id", ["cluster_id"], unique=False)
        batch_op.create_index("idx_decision_logs_evaluated_at", ["evaluated_at"], unique=False)

    op.create_table(
        "plant_health_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plant_id", sa.Integer(), nullable=False),
        sa.Column("date_key", sa.String(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("soil_in_band_pct", sa.Float(), nullable=True),
        sa.Column("temp_in_band_pct", sa.Float(), nullable=True),
        sa.Column("humidity_in_band_pct", sa.Float(), nullable=True),
        sa.Column("efficiency", sa.Float(), nullable=True),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plant_id", "date_key"),
    )
    with op.batch_alter_table("plant_health_daily", schema=None) as batch_op:
        batch_op.create_index("idx_plant_health_daily_plant", ["plant_id"], unique=False)

    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("units", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("theme", sa.String(), nullable=False),
        sa.Column("default_cluster_id", sa.Integer(), nullable=True),
        sa.Column("refresh_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("dry_run_global", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vacation_windows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.Integer(), nullable=False),
        sa.Column("ends_at", sa.Integer(), nullable=False),
        sa.Column("contact_email", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "irrigation_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("interval_hours", sa.Integer(), nullable=True),
        sa.Column("auto_run", sa.Boolean(), nullable=False),
        sa.Column("last_updated", sa.Integer(), nullable=False),
        sa.Column("daily_cap_minutes", sa.Integer(), nullable=True),
        sa.Column("max_events_per_day", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cluster_id"),
    )
    op.create_table(
        "irrigators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("tuya_device_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("config", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tuya_device_id"),
    )
    op.create_table(
        "plants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("species", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("water_needs", sa.String(), nullable=True),
        sa.Column("light_needs", sa.String(), nullable=True),
        sa.Column("ideal_temp_min", sa.Float(), nullable=True),
        sa.Column("ideal_temp_max", sa.Float(), nullable=True),
        sa.Column("ideal_humidity_min", sa.Float(), nullable=True),
        sa.Column("ideal_humidity_max", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "irrigation_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("irrigator_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("triggered_by", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["irrigator_id"],
            ["irrigators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("irrigation_events", schema=None) as batch_op:
        batch_op.create_index("idx_irrigation_events_irrigator_id", ["irrigator_id"], unique=False)
        batch_op.create_index("idx_irrigation_events_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "sensors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("tuya_device_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("config", sa.String(), nullable=True),
        sa.Column("plant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tuya_device_id"),
    )
    op.create_table(
        "sensor_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sensor_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("soil_moisture", sa.Float(), nullable=True),
        sa.Column("light", sa.Integer(), nullable=True),
        sa.Column("env_humidity", sa.Float(), nullable=True),
        sa.Column("battery_state", sa.String(), nullable=True),
        sa.Column("water_warning", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sensor_id", "timestamp"),
    )
    with op.batch_alter_table("sensor_readings", schema=None) as batch_op:
        batch_op.create_index("idx_sensor_readings_sensor_id", ["sensor_id"], unique=False)
        batch_op.create_index("idx_sensor_readings_timestamp", ["timestamp"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensor_readings", schema=None) as batch_op:
        batch_op.drop_index("idx_sensor_readings_timestamp")
        batch_op.drop_index("idx_sensor_readings_sensor_id")

    op.drop_table("sensor_readings")
    op.drop_table("sensors")
    with op.batch_alter_table("irrigation_events", schema=None) as batch_op:
        batch_op.drop_index("idx_irrigation_events_timestamp")
        batch_op.drop_index("idx_irrigation_events_irrigator_id")

    op.drop_table("irrigation_events")
    op.drop_table("plants")
    op.drop_table("irrigators")
    op.drop_table("irrigation_configs")
    op.drop_table("vacation_windows")
    op.drop_table("user_preferences")
    with op.batch_alter_table("plant_health_daily", schema=None) as batch_op:
        batch_op.drop_index("idx_plant_health_daily_plant")

    op.drop_table("plant_health_daily")
    with op.batch_alter_table("decision_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_decision_logs_evaluated_at")
        batch_op.drop_index("idx_decision_logs_cluster_id")

    op.drop_table("decision_logs")
    op.drop_table("clusters")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index("idx_alerts_status")
        batch_op.drop_index("idx_alerts_entity")
        batch_op.drop_index("idx_alerts_dedup_key")

    op.drop_table("alerts")
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.drop_index("idx_activity_events_timestamp")
        batch_op.drop_index("idx_activity_events_source")
        batch_op.drop_index("idx_activity_events_entity")

    op.drop_table("activity_events")
    # ### end Alembic commands ###
